main: net.jandie1505.bedwars.Bedwars
name: Bedwars
version: 1.0
api-version: 1.21
permissions:
  bedwars.fulljoin:
    default: op
    description: allows to join full servers
  bedwars.admin:
    default: op
    description: admin permission
  bedwars.*:
    default: op
    children:
      - bedwars.fulljoin
      - bedwars.admin
    description: wildcard permission
commands:
  bedwars:
    description: main command
    usage: /bedwars
  start:
    description: force-start a game
    usage: /start
author: jandie1505
website: jandie1505.net